// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByi4oGRi1O6Ft1yMwjrlPvGpIXKEUWl9U',
    appId: '1:662452778435:web:65870903b3463125e03976',
    messagingSenderId: '662452778435',
    projectId: 'glint-budget-5555',
    authDomain: 'glint-budget-5555.firebaseapp.com',
    storageBucket: 'glint-budget-5555.firebasestorage.app',
    measurementId: 'G-D87ZJEHMGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWK02qIOzdTDVGb6LdobYI2YfH1Y2qUn0',
    appId: '1:662452778435:android:bebb643b8cdf1ea8e03976',
    messagingSenderId: '662452778435',
    projectId: 'glint-budget-5555',
    storageBucket: 'glint-budget-5555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKrXf3hWeBN9-VpRgwZzKSEe4_ppFssL8',
    appId: '1:662452778435:ios:a7370318e4b72bdbe03976',
    messagingSenderId: '662452778435',
    projectId: 'glint-budget-5555',
    storageBucket: 'glint-budget-5555.firebasestorage.app',
    androidClientId: '662452778435-v8huugkjclebcnmihcbnrcnaf9u0bmhk.apps.googleusercontent.com',
    iosClientId: '662452778435-13vns5jrvbi48hhl3gsb25ev98lko8gf.apps.googleusercontent.com',
    iosBundleId: 'com.glintbudget.glintbudgetone',
  );

}