import 'models/currency.dart';

const List<Currency> kCurrencies = [
  Currency(name: 'US Dollar',          code: 'USD', symbol: '\$'),
  Currency(name: 'Euro',               code: 'EUR', symbol: '€'),
  Currency(name: 'British Pound',      code: 'GBP', symbol: '£'),
  Currency(name: 'Singapore Dollar',   code: 'SGD', symbol: 'S\$'),
  Currency(name: 'Australian Dollar',  code: 'AUD', symbol: 'A\$'),
  Currency(name: 'Canadian Dollar',    code: 'CAD', symbol: 'C\$'),
  Currency(name: 'Japanese Yen',       code: 'JPY', symbol: '¥'),
  Currency(name: 'Chinese Yuan',       code: 'CNY', symbol: '¥'),
  Currency(name: 'Indian Rupee',       code: 'INR', symbol: '₹'),
  Currency(name: 'Swiss Franc',        code: 'CHF', symbol: 'CHF'),
  Currency(name: 'Hong Kong Dollar',   code: 'HKD', symbol: 'HK\$'),
  Currency(name: 'South Korean Won',   code: 'KRW', symbol: '₩'),
  Currency(name: 'Malaysian Ringgit',  code: 'MYR', symbol: 'RM'),
  Currency(name: 'Thai Baht',          code: 'THB', symbol: '฿'),
  Currency(name: 'Indonesian Rupiah',  code: 'IDR', symbol: 'Rp'),
  Currency(name: 'Philippine Peso',    code: 'PHP', symbol: '₱'),
  Currency(name: 'Vietnamese Dong',    code: 'VND', symbol: '₫'),
  Currency(name: 'New Zealand Dollar', code: 'NZD', symbol: 'NZ\$'),
  Currency(name: 'Swedish Krona',      code: 'SEK', symbol: 'kr'),
  Currency(name: 'Norwegian Krone',    code: 'NOK', symbol: 'kr'),
  Currency(name: 'Danish Krone',       code: 'DKK', symbol: 'kr'),
  Currency(name: 'Mexican Peso',       code: 'MXN', symbol: 'MX\$'),
  Currency(name: 'Brazilian Real',     code: 'BRL', symbol: 'R\$'),
  Currency(name: 'South African Rand', code: 'ZAR', symbol: 'R'),
  Currency(name: 'UAE Dirham',         code: 'AED', symbol: 'AED'),
  Currency(name: 'Saudi Riyal',        code: 'SAR', symbol: 'SAR'),
  Currency(name: 'Turkish Lira',       code: 'TRY', symbol: '₺'),
  Currency(name: 'Russian Ruble',      code: 'RUB', symbol: '₽'),
  Currency(name: 'Polish Zloty',       code: 'PLN', symbol: 'zł'),
  Currency(name: 'Czech Koruna',       code: 'CZK', symbol: 'Kč'),
];
